config/routes.rb
CaducesApp::Application.routes.draw do
  resources :famtrees

  resources :people

  get "people/new"

  resources :medevents

end

app/models/medevent.rb
class Medevent < ActiveRecord::Base
end

app/models/person.rb
require 'json'
class Person < ActiveRecord::Base
  



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/medevents_controller.rb
class MedeventsController < ApplicationController
  # GET /medevents
  # GET /medevents.xml
  def index
    @medevents = Medevent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @medevents }
    end
  end

  # GET /medevents/1
  # GET /medevents/1.xml
  def show
    @medevent = Medevent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @medevent }
    end
  end

  # GET /medevents/new
  # GET /medevents/new.xml
  def new
    @medevent = Medevent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @medevent }
    end
  end

  # GET /medevents/1/edit
  def edit
    @medevent = Medevent.find(params[:id])
  end

  # POST /medevents
  # POST /medevents.xml
  def create
    @medevent = Medevent.new(params[:medevent])

    respond_to do |format|
      if @medevent.save
        format.html { redirect_to(@medevent, :notice => 'Medevent was successfully created.') }
        format.xml  { render :xml => @medevent, :status => :created, :location => @medevent }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @medevent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /medevents/1
  # PUT /medevents/1.xml
  def update
    @medevent = Medevent.find(params[:id])

    respond_to do |format|
      if @medevent.update_attributes(params[:medevent])
        format.html { redirect_to(@medevent, :notice => 'Medevent was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @medevent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /medevents/1
  # DELETE /medevents/1.xml
  def destroy
    @medevent = Medevent.find(params[:id])
    @medevent.destroy

    respond_to do |format|
      format.html { redirect_to(medevents_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medevents_helper.rb
module MedeventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaducesApp</title>
  <%= stylesheet_link_tag :all, :recursive => true%>
  <%= javascript_include_tag :defaults, :recursive => true%>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medevents/_form.html.erb
<%= form_for(@medevent) do |f| %>
  <% if @medevent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medevent.errors.count, "error") %> prohibited this medevent from being saved:</h2>

      <ul>
      <% @medevent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :importance %><br />
    <%= f.text_field :importance %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medevents/edit.html.erb
<h1>Editing medevent</h1>

<%= render 'form' %>

<%= link_to 'Show', @medevent %> |
<%= link_to 'Back', medevents_path %>

app/views/medevents/index.html.erb
<h1>Listing medevents</h1>

<!-- TIMEGLIDER PLACEMENT: Put the intended location for the timeline  
     directly above the data table -->
<div id='placement'></div>

<table class='timeline-table' id="myMedEvents" focus_date="2011-05-15"
title="my life" initial_zoom="48" description="The Wild and Wooly times of James Davis.">
<!-- The first row of the table is reserved for meta-data.
    
     Class values below are *critical* for mapping out data from the 
     <td> elements that follow ---  though order is not important.
     The text in <td> elements is *not* critical: just the class names.
-->
<tr>
  <th class="tg-startdate">start date</th>
  <th class="tg-enddate">end date</th>
  <th class="tg-title">title</th>
  <th class="tg-description">description</th>
  <th class="tg-icon">icon</th>
  <th class="tg-importance">importance</th>
  <th class="tg-link">link</th>	
</tr>


<% @medevents.each do |medevent| %>
  <tr>
    <td><%= medevent.start_date %></td>
    <td><%= medevent.end_date %></td>
    <td><%= medevent.title %></td>
    <td><%= medevent.description %></td>
	<td>images/timeglider/icons/circle_green.png</td>
    <td><%= medevent.importance %></td>
	<td><%= edit_medevent_path(medevent) %></td>
    <!--><td><%= link_to 'Show', medevent %></td>
    <td><%= link_to 'Edit', edit_medevent_path(medevent) %></td>
    <td><%= link_to 'Destroy', medevent, :confirm => 'Are you sure?', :method => :delete %></td>-->
  </tr>
<% end %>
</table>


<!-- 3rd party libs -->
    <script src="javascripts/jquery-1.4.4.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="javascripts/jquery-ui-1.8.9.custom.min.js" type="text/javascript" charset="utf-8"></script>

    <!-- FRIEND LIBS -->
    <script src="javascripts/underscore-min.js" type="text/javascript" charset="utf-8"></script>

	<script src="javascripts/backbone-min.js" type="text/javascript" charset="utf-8"></script>
	<script src="javascripts/jquery.global.js" type="text/javascript" charset="utf-8"></script>
	<script src="javascripts/jquery.tmpl.js" type="text/javascript" charset="utf-8"></script>
	<script src="javascripts/ba-debug.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="javascripts/ba-tinyPubSub.js" type="text/javascript" charset="utf-8"></script>
	<script src="javascripts/jquery.mousewheel.min.js" type="text/javascript" charset="utf-8"></script>

	<script src="javascripts/jquery.ui.ipad.js" type="text/javascript" charset="utf-8"></script>
	<script src="javascripts/raphael-min.js" type="text/javascript" charset="utf-8"></script>

	    
	<!-- TIMEGLIDER -->
	<script src="javascripts/timeglider/TG_Date.js" type="text/javascript" charset="utf-8"></script>
    <script src="javascripts/timeglider/TG_Org.js" type="text/javascript" charset="utf-8"></script>
	<script src="javascripts/timeglider/TG_Timeline.js" type="text/javascript" charset="utf-8"></script> 
	<script src="javascripts/timeglider/TG_TimelineView.js" type="text/javascript" charset="utf-8"></script>

	<script src="javascripts/timeglider/TG_Mediator.js" type="text/javascript" charset="utf-8"></script> 
	<script src="javascripts/timeglider/timeglider.timeline.widget.js" type="text/javascript" charset="utf-8"></script>

  <script>

	$(document).ready(function () { 
		
		var tld = "timeline";
		
		var tg1 = $("#placement").timeline({
				"min_zoom":18, 
				"max_zoom":55, 
				// data source is the id of the table!
				"data_source":"#myMedEvents"
		});
		
		
		$("#toggle").click(function () { 
			if (tld == "timeline") {
				$("#placement").css({"display":"none"});
				$(".timeline-table").css({"display":"block"});
				tld = "table";
			} else {
				$("#placement").css({"display":"block"});
				$(".timeline-table").css({"display":"none"});
				
				tld = "timeline";
			}
			
		});
		
		
    }); // end document-ready
	
</script>

    


<script type='text/javascript'>
	$(document).ready(function () {
		$("li#table").addClass("nav-active");
	});


  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-8964270-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</br>
<%= link_to 'New Medevent', new_medevent_path %>

app/views/medevents/new.html.erb
<h1>New medevent</h1>

<%= render 'form' %>

<%= link_to 'Back', medevents_path %>

app/views/medevents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @medevent.title %>
</p>

<p>
  <b>Description:</b>
  <%= @medevent.description %>
</p>

<p>
  <b>Importance:</b>
  <%= @medevent.importance %>
</p>

<p>
  <b>Start date:</b>
  <%= @medevent.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @medevent.end_date %>
</p>


<%= link_to 'Edit', edit_medevent_path(@medevent) %> |
<%= link_to 'Back', medevents_path %>

app/views/people/index.html.erb
<h1>Family Tree</h1>

<!-- CSS Files -->
<link type="text/css" href="stylesheets/tree/base.css" rel="stylesheet" />
<link type="text/css" href="stylesheets/tree/Spacetree.css" rel="stylesheet" />

<!--[if IE]><script language="javascript" type="text/javascript" src="../../Extras/excanvas.js"></script><![endif]-->

<!-- JIT Library File -->
<script language="javascript" type="text/javascript" src="javascripts/tree/jit-yc.js"></script>

<!-- Example File -->
<script language="javascript" type="text/javascript" src="javascripts/tree/example2.js"></script>

<script language="javascript" type="text/javascript">document.observe('dom:loaded', function() {
init();});
</script>



<div id="container" >

<div id="left-container">



<div class="text">
<h4>
Tree Animation    
</h4> 

            A static JSON Tree structure is used as input for this animation.<br /><br />

            <b>Click</b> on a node to select it.<br /><br />
            You can <b>select the tree orientation</b> by changing the select box in the right column.<br /><br />
            You can <b>change the selection mode</b> from <em>Normal</em> selection (i.e. center the selected node) to 
            <em>Set as Root</em>.<br /><br />

            <b>Drag and Drop the canvas</b> to do some panning.<br /><br />
            Leaves color depend on the number of children they actually have.
            
</div>

<div id="id-list"></div>


<div style="text-align:center;"><a href="example1.code.html">See the Example Code</a></div>
</div>

<div id="center-container">

    <div id="infovis"></div>    
</div>

<div id="right-container">

<h4>Tree Orientation</h4>
<table>
    <tr>
        <td>
            <label for="r-left">Left </label>
        </td>

        <td>
            <input type="radio" id="r-left" name="orientation" checked="checked" value="left" />
        </td>
    </tr>
    <tr>
         <td>
            <label for="r-top">Top </label>
         </td>

         <td>
            <input type="radio" id="r-top" name="orientation" value="top" />
         </td>
    </tr>
    <tr>
         <td>
            <label for="r-bottom">Bottom </label>
          </td>

          <td>
            <input type="radio" id="r-bottom" name="orientation" value="bottom" />
          </td>
    </tr>
    <tr>
          <td>
            <label for="r-right">Right </label>
          </td> 
          <td> 
           <input type="radio" id="r-right" name="orientation" value="right" />

          </td>
    </tr>
</table>

<h4>Selection Mode</h4>
<table>
    <tr>
        <td>
            <label for="s-normal">Normal </label>
        </td>

        <td>
            <input type="radio" id="s-normal" name="selection" checked="checked" value="normal" />
        </td>
    </tr>
    <tr>
         <td>
            <label for="s-root">Set as Root </label>
         </td>

         <td>
            <input type="radio" id="s-root" name="selection" value="root" />
         </td>
    </tr>
</table>

</div>

<div id="log"></div>
</div>